# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - powerarm_controller

  powerarm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - shoulder_joint_1
      - shoulder_joint_2
      - shoulder_joint_3
      - elbow_joint
    action_ns: follow_joint_trajectory
    default: true