# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    powerarm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

powerarm_controller:
  ros__parameters:
    joints:
      - shoulder_joint_1
      - shoulder_joint_2
      - shoulder_joint_3
      - elbow_joint
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
